<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;

use App\Models\Restaurant;
use App\Models\Room;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        DB::table('room_types')->insert([
            ['room_type_id' => 1, 'max_capacity' => 3, 'price' => 15800.00, 'description' => 'Host intimate dinners at the 4-seater dining table. Rejuvenate your senses in the luxurious 2-person marble bathtub. Get ready for any occasion with a walk-in wardrobe and dedicated dressing table.', 'view' => 'City View', 'bath_amenities' => 'Glass-enclosed shower', 'sqm' => '95 sqm on average', 'layout' => '1 king or 2 queen beds'],
            ['room_type_id' => 2, 'max_capacity' => 3, 'price' => 19400.00, 'description' => 'Host intimate dinners at the 4-seater dining table. Rejuvenate your senses in the luxurious 2-person marble bathtub. Get ready for any occasion with a walk-in wardrobe and dedicated dressing table.', 'view' => 'City View', 'bath_amenities' => 'Deep-soaking bathtub', 'sqm' => '95 sqm on average', 'layout' => '1 king or 2 queen beds'],
            ['room_type_id' => 3, 'max_capacity' => 3, 'price' => 20000.00, 'description' => 'Host intimate dinners at the 4-seater dining table. Rejuvenate your senses in the luxurious 2-person marble bathtub. Get ready for any occasion with a walk-in wardrobe and dedicated dressing table.', 'view' => 'City View', 'bath_amenities' => 'Jacuzzi', 'sqm' => '95 sqm on average', 'layout' => '1 king or 2 queen beds'],
            ['room_type_id' => 4, 'max_capacity' => 3, 'price' => 18000.00, 'description' => 'Host intimate dinners at the 4-seater dining table. Rejuvenate your senses in the luxurious 2-person marble bathtub. Get ready for any occasion with a walk-in wardrobe and dedicated dressing table.', 'view' => 'Garden View', 'bath_amenities' => 'Glass-enclosed shower', 'sqm' => '95 sqm on average', 'layout' => '1 king or 2 queen beds'],
            ['room_type_id' => 5, 'max_capacity' => 3, 'price' => 19000.00, 'description' => 'Host intimate dinners at the 4-seater dining table. Rejuvenate your senses in the luxurious 2-person marble bathtub. Get ready for any occasion with a walk-in wardrobe and dedicated dressing table.', 'view' => 'Garden View', 'bath_amenities' => 'Deep-soaking bathtub', 'sqm' => '95 sqm on average', 'layout' => '1 king or 2 queen beds'],
            ['room_type_id' => 6, 'max_capacity' => 3, 'price' => 20000.00, 'description' => 'Host intimate dinners at the 4-seater dining table. Rejuvenate your senses in the luxurious 2-person marble bathtub. Get ready for any occasion with a walk-in wardrobe and dedicated dressing table.', 'view' => 'Garden View', 'bath_amenities' => 'Jacuzzi', 'sqm' => '95 sqm on average', 'layout' => '1 king or 2 queen beds'],
            ['room_type_id' => 7, 'max_capacity' => 4, 'price' => 20000.00, 'description' => 'Travelling with the little ones is a breeze with the fully equipped kitchenette and washer. Create cherished memories and enjoy endless hours of family fun with our exclusively curated Adventure Pack.', 'view' => 'Garden View', 'bath_amenities' => 'Glass-enclosed shower', 'sqm' => '75 – 95 sqm on average', 'layout' => '1 living room & 2 bedrooms'],
            ['room_type_id' => 8, 'max_capacity' => 4, 'price' => 21400.00, 'description' => 'Travelling with the little ones is a breeze with the fully equipped kitchenette and washer. Create cherished memories and enjoy endless hours of family fun with our exclusively curated Adventure Pack.', 'view' => 'Garden View', 'bath_amenities' => 'Deep-soaking bathtub', 'sqm' => '75 – 95 sqm on average', 'layout' => '1 living room & 2 bedrooms'],
            ['room_type_id' => 9, 'max_capacity' => 4, 'price' => 25000.00, 'description' => 'Travelling with the little ones is a breeze with the fully equipped kitchenette and washer. Create cherished memories and enjoy endless hours of family fun with our exclusively curated Adventure Pack.', 'view' => 'Garden View', 'bath_amenities' => 'Jacuzzi', 'sqm' => '75 – 95 sqm on average', 'layout' => '1 living room & 2 bedrooms'],
            ['room_type_id' => 11, 'max_capacity' => 3, 'price' => 155000.00, 'description' => 'An exquisitely designed and artfully curated haven of calm in the heart of the city. Take a long bath in your expansive bathroom fitted with a concealed TV, and indulge in the generous curation of treasures in the bespoke Armoire.', 'view' => 'Sea-side View', 'bath_amenities' => 'Glass-enclosed shower', 'sqm' => '55 sqm on average', 'layout' => '1 king bed'],
            ['room_type_id' => 12, 'max_capacity' => 3, 'price' => 18400.00, 'description' => 'An exquisitely designed and artfully curated haven of calm in the heart of the city. Take a long bath in your expansive bathroom fitted with a concealed TV, and indulge in the generous curation of treasures in the bespoke Armoire.', 'view' => 'Sea-side View', 'bath_amenities' => 'Deep-soaking bathtub', 'sqm' => '55 sqm on average', 'layout' => '1 king bed'],
            ['room_type_id' => 13, 'max_capacity' => 3, 'price' => 20000.00, 'description' => 'An exquisitely designed and artfully curated haven of calm in the heart of the city. Take a long bath in your expansive bathroom fitted with a concealed TV, and indulge in the generous curation of treasures in the bespoke Armoire.', 'view' => 'Sea-side View', 'bath_amenities' => 'Jacuzzi', 'sqm' => '55 sqm on average', 'layout' => '1 king bed'],
            ['room_type_id' => 14, 'max_capacity' => 3, 'price' => 15800.00, 'description' => 'An exquisitely designed and artfully curated haven of calm in the heart of the city. Take a long bath in your expansive bathroom fitted with a concealed TV, and indulge in the generous curation of treasures in the bespoke Armoire.', 'view' => 'City View', 'bath_amenities' => 'Glass-enclosed shower', 'sqm' => '55 sqm on average', 'layout' => '1 king bed'],
            ['room_type_id' => 15, 'max_capacity' => 3, 'price' => 18800.00, 'description' => 'An exquisitely designed and artfully curated haven of calm in the heart of the city. Take a long bath in your expansive bathroom fitted with a concealed TV, and indulge in the generous curation of treasures in the bespoke Armoire.', 'view' => 'City View', 'bath_amenities' => 'Deep-soaking bathtub', 'sqm' => '55 sqm on average', 'layout' => '1 king bed'],
            ['room_type_id' => 16, 'max_capacity' => 3, 'price' => 21000.00, 'description' => 'An exquisitely designed and artfully curated haven of calm in the heart of the city. Take a long bath in your expansive bathroom fitted with a concealed TV, and indulge in the generous curation of treasures in the bespoke Armoire.', 'view' => 'City View', 'bath_amenities' => 'Jacuzzi', 'sqm' => '55 sqm on average', 'layout' => '1 king bed'],
            ['room_type_id' => 17, 'max_capacity' => 6, 'price' => 25000.00, 'description' => 'A bespoke urban sanctuary, designed to pamper and lift your senses. Rejuvenate in your expansive bathroom with enhanced shower facilities, and revel in the suite life with dedicated living and dining areas. A specialty night fridge rests at the entrance of the bedroom, stocked with premium mineral waters.', 'view' => 'Sea-side View', 'bath_amenities' => 'Glass-enclosed shower', 'sqm' => '100 sqm on average', 'layout' => '1 living room & 1 or 2 bedrooms'],
            ['room_type_id' => 18, 'max_capacity' => 6, 'price' => 27000.00, 'description' => 'A bespoke urban sanctuary, designed to pamper and lift your senses. Rejuvenate in your expansive bathroom with enhanced shower facilities, and revel in the suite life with dedicated living and dining areas. A specialty night fridge rests at the entrance of the bedroom, stocked with premium mineral waters.', 'view' => 'Sea-side View', 'bath_amenities' => 'Deep-soaking bathtub', 'sqm' => '100 sqm on average', 'layout' => '1 living room & 1 or 2 bedrooms'],
            ['room_type_id' => 19, 'max_capacity' => 6, 'price' => 29200.00, 'description' => 'A bespoke urban sanctuary, designed to pamper and lift your senses. Rejuvenate in your expansive bathroom with enhanced shower facilities, and revel in the suite life with dedicated living and dining areas. A specialty night fridge rests at the entrance of the bedroom, stocked with premium mineral waters.', 'view' => 'Sea-side View', 'bath_amenities' => 'Jacuzzi', 'sqm' => '100 sqm on average', 'layout' => '1 living room & 1 or 2 bedrooms'],
            ['room_type_id' => 20, 'max_capacity' => 6, 'price' => 21400.00, 'description' => 'A bespoke urban sanctuary, designed to pamper and lift your senses. Rejuvenate in your expansive bathroom with enhanced shower facilities, and revel in the suite life with dedicated living and dining areas. A specialty night fridge rests at the entrance of the bedroom, stocked with premium mineral waters.', 'view' => 'City View', 'bath_amenities' => 'Glass-enclosed shower', 'sqm' => '100 sqm on average', 'layout' => '1 living room & 1 or 2 bedrooms'],
            ['room_type_id' => 21, 'max_capacity' => 6, 'price' => 23200.00, 'description' => 'A bespoke urban sanctuary, designed to pamper and lift your senses. Rejuvenate in your expansive bathroom with enhanced shower facilities, and revel in the suite life with dedicated living and dining areas. A specialty night fridge rests at the entrance of the bedroom, stocked with premium mineral waters.', 'view' => 'City View', 'bath_amenities' => 'Deep-soaking bathtub', 'sqm' => '100 sqm on average', 'layout' => '1 living room & 1 or 2 bedrooms'],
            ['room_type_id' => 22, 'max_capacity' => 6, 'price' => 25000.00, 'description' => 'A bespoke urban sanctuary, designed to pamper and lift your senses. Rejuvenate in your expansive bathroom with enhanced shower facilities, and revel in the suite life with dedicated living and dining areas. A specialty night fridge rests at the entrance of the bedroom, stocked with premium mineral waters.', 'view' => 'Sea-side View', 'bath_amenities' => 'Jacuzzi', 'sqm' => '100 sqm on average', 'layout' => '1 living room & 1 or 2 bedrooms'],
            ['room_type_id' => 23, 'max_capacity' => 3, 'price' => 12000.00, 'description' => 'Wake up to magnificent views of Gardens by the Bay or the city in your room with floor-to-ceiling windows.', 'view' => 'Garden View', 'bath_amenities' => 'Glass-enclosed shower', 'sqm' => '35 sqm on average', 'layout' => '1 king or 2 single beds'],
            ['room_type_id' => 24, 'max_capacity' => 3, 'price' => 14000.00, 'description' => 'Wake up to magnificent views of Gardens by the Bay or the city in your room with floor-to-ceiling windows.', 'view' => 'Garden View', 'bath_amenities' => 'Deep-soaking bathtub', 'sqm' => '35 sqm on average', 'layout' => '1 king or 2 single beds'],
            ['room_type_id' => 25, 'max_capacity' => 3, 'price' => 15800.00, 'description' => 'Wake up to magnificent views of Gardens by the Bay or the city in your room with floor-to-ceiling windows.', 'view' => 'Garden View', 'bath_amenities' => 'Jacuzzi', 'sqm' => '35 sqm on average', 'layout' => '1 king or 2 single beds'],
            ['room_type_id' => 26, 'max_capacity' => 3, 'price' => 12800.00, 'description' => 'Wake up to magnificent views of Gardens by the Bay or the city in your room with floor-to-ceiling windows.', 'view' => 'City View', 'bath_amenities' => 'Glass-enclosed shower', 'sqm' => '35 sqm on average', 'layout' => '1 king or 2 single beds'],
            ['room_type_id' => 27, 'max_capacity' => 3, 'price' => 14800.00, 'description' => 'Wake up to magnificent views of Gardens by the Bay or the city in your room with floor-to-ceiling windows.', 'view' => 'City View', 'bath_amenities' => 'Deep-soaking bathtub', 'sqm' => '35 sqm on average', 'layout' => '1 king or 2 single beds'],
            ['room_type_id' => 28, 'max_capacity' => 3, 'price' => 15500.00, 'description' => 'Wake up to magnificent views of Gardens by the Bay or the city in your room with floor-to-ceiling windows.', 'view' => 'City View', 'bath_amenities' => 'Jacuzzi', 'sqm' => '35 sqm on average', 'layout' => '1 king or 2 single beds'],
            ['room_type_id' => 29, 'max_capacity' => 3, 'price' => 13000.00, 'description' => 'Retreat into your private haven, fitted with a deep soaking bathtub to soothe away the day’s tension.', 'view' => 'Garden View', 'bath_amenities' => 'Glass-enclosed shower', 'sqm' => '40 sqm on average', 'layout' => '1 king or 2 single beds'],
            ['room_type_id' => 30, 'max_capacity' => 3, 'price' => 14200.00, 'description' => 'Retreat into your private haven, fitted with a deep soaking bathtub to soothe away the day’s tension.', 'view' => 'Garden View', 'bath_amenities' => 'Deep-soaking bathtub', 'sqm' => '40 sqm on average', 'layout' => ''],
            ['room_type_id' => 31, 'max_capacity' => 3, 'price' => 16800.00, 'description' => 'Retreat into your private haven, fitted with a deep soaking bathtub to soothe away the day’s tension.', 'view' => 'Garden View', 'bath_amenities' => 'Jacuzzi', 'sqm' => '40 sqm on average', 'layout' => '1 king or 2 single beds'],
            ['room_type_id' => 32, 'max_capacity' => 3, 'price' => 13400.00, 'description' => 'Retreat into your private haven, fitted with a deep soaking bathtub to soothe away the day’s tension.', 'view' => 'City View', 'bath_amenities' => 'Glass-enclosed shower', 'sqm' => '40 sqm on average', 'layout' => '1 king or 2 single beds'],
            ['room_type_id' => 33, 'max_capacity' => 3, 'price' => 14860.00, 'description' => 'Retreat into your private haven, fitted with a deep soaking bathtub to soothe away the day’s tension.', 'view' => 'City View', 'bath_amenities' => 'Deep-soaking bathtub', 'sqm' => '40 sqm on average', 'layout' => '1 king or 2 single beds'],
            ['room_type_id' => 34, 'max_capacity' => 3, 'price' => 15920.00, 'description' => 'Retreat into your private haven, fitted with a deep soaking bathtub to soothe away the day’s tension.', 'view' => 'City View', 'bath_amenities' => 'Jacuzzi', 'sqm' => '40 sqm on average', 'layout' => '1 king or 2 single beds'],
            ['room_type_id' => 35, 'max_capacity' => 3, 'price' => 15600.00, 'description' => 'Generous in space, with a separate living area and a spa-inspired marble bathroom.', 'view' => 'City View', 'bath_amenities' => 'Glass-enclosed shower', 'sqm' => '70 sqm on average', 'layout' => '1 living room & 1 bedroom'],
            ['room_type_id' => 36, 'max_capacity' => 3, 'price' => 16800.00, 'description' => 'Generous in space, with a separate living area and a spa-inspired marble bathroom.', 'view' => 'City View', 'bath_amenities' => 'Deep-soaking bathtub', 'sqm' => '70 sqm on average', 'layout' => '1 living room & 1 bedroom'],
            ['room_type_id' => 37, 'max_capacity' => 3, 'price' => 17480.00, 'description' => 'Generous in space, with a separate living area and a spa-inspired marble bathroom.', 'view' => 'City View', 'bath_amenities' => 'Jacuzzi', 'sqm' => '70 sqm on average', 'layout' => '1 living room & 1 bedroom'],
            ['room_type_id' => 38, 'max_capacity' => 3, 'price' => 11000.00, 'description' => 'Generous in space, with a separate living area and a spa-inspired marble bathroom.', 'view' => '', 'bath_amenities' => 'Glass-enclosed shower', 'sqm' => '70 sqm on average', 'layout' => '1 living room & 1 bedroom'],
            ['room_type_id' => 39, 'max_capacity' => 3, 'price' => 12450.00, 'description' => 'Generous in space, with a separate living area and a spa-inspired marble bathroom.', 'view' => '', 'bath_amenities' => 'Deep-soaking bathtub', 'sqm' => '70 sqm on average', 'layout' => '1 living room & 1 bedroom'],
            ['room_type_id' => 40, 'max_capacity' => 3, 'price' => 13000.00, 'description' => 'Generous in space, with a separate living area and a spa-inspired marble bathroom.', 'view' => '', 'bath_amenities' => 'Jacuzzi', 'sqm' => '70 sqm on average', 'layout' => '1 living room & 1 bedroom'],
        ]);

        $restaurants = [
            [
                'restaurant_name' => 'ANGELINA',
                'time_open' => '11:00 AM',
                'time_close' => '10:00 PM',
                'restaurant_type' => 'WESTERN | CAFÉ | CASUAL | DINING',
                'contact_email' => 'Angelina@hoteldulluna.com',
                'contact_number' => '+65 6688 7218',
                'description' => 'Made from meringue, light whipped cream and chestnut paste vermicelli, the Mont-Blanc is an Angelina classic. Other pastries the tearoom is known for include the Éclair Chocolat and Paris-New York. Founded in 1903 by Austrian confectioner Antoine Rumpelmayer and named in honour of his daughter-in-law, Angelina also offers breakfast items, pastas and high tea sets.',
                'location' => 'B2-89, The Shoppes\r\nNearest carpark: Central (Orange zone)',
                'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314055/Dining/angelina-1920x1080-3_o5bder.jpg',
            ],
            [
                'restaurant_name' => 'BACHA COFFEE',
                'time_open' => '10:00 AM',
                'time_close' => '10:00 PM',
                'restaurant_type' => 'WESTERN | CAFÉ | CASUAL DINING',
                'contact_email' => 'bachacoffee@hoteldelluna.com',
                'contact_number' => '+65 6560 1910',
                'description' => 'Bacha Coffee presents Fashion Avenue, the world\'s first destination to offer their coffee room, takeaway experience, and boutique all in one spectacular location. Fashion Avenue houses their entire collection of over 200 coffees, from Single Origin, Fine Blended, Fine Flavoured to CO2 Decaffeinated varieties.',
                'location' => 'B2-13/14, The Shoppes\r\nNearest carpark: Central (Orange zone)',
                'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314060/Dining/bacha-coffee-gallery-4_w9aev8.jpg',
            ],
            [
                'restaurant_name' => 'BEANSTRO',
                'time_open' => '08:30 AM',
                'time_close' => '10:30 PM',
                'restaurant_type' => 'HALAL | WESTERN | CAFÉ',
                'contact_email' => 'beanstro@hoteldelluna.com',
                'contact_number' => '+65 6688 7001',
                'description' => 'Bask in the good vibes at Beanstro, with its chic interior designed to create a stylish getaway in the heart of Singapore. Indulge in a delicious adventure with hearty treats such as Tiger Prawns Aglio Olio, Red Snapper Fish & Chips, Classic Burger and more! You can also experience the theatricality of Balancing Siphon coffee brewing method here.',
                'location' => 'B2-20, The Shoppes\r\nNearest carpark: Central (Orange zone)',
                'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314066/Dining/beanstro-1920x1080-hero_r8vwpq.jpg',
            ],
            [
                'restaurant_name' => 'BLACK TAP CRAFT BURGERS & BEER',
                'time_open' => '11:30 AM',
                'time_close' => '10:30 PM',
                'restaurant_type' => 'WESTERN | CASUAL DINING | BAR',
                'contact_email' => '',
                'contact_number' => '',
                'description' => 'Feast on award-winning burgers, towering milkshakes, craft beers, and cocktails at the first Asian flagship of this New York City institution. Black Tap brings a timeless NYC vibe to Singapore, rocking an old-school hip-hop soundtrack and a bespoke mural by local artist @has.j. The menu features a wide selection of craft burgers.',
                'location' => 'L1-80, The Shoppes\r\nNearest carpark: South (Blue zone)',
                'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314074/Dining/black-tap-gallery-1920x1080-8_d1hecy.jpg',
            ],
            [
                'restaurant_name' => 'BLOSSOM',
                'time_open' => '11:00 AM',
                'time_close' => '09:45 PM',
                'restaurant_type' => 'CHINESE | OTHER ASIAN | VEGETARIAN | FINE DINING | BAR',
                'contact_email' => 'info@blossomrestaurant.com',
                'contact_number' => '+65 6688 7799',
                'description' => 'Contemporary Chinese restaurant BLOSSOM offers modern interpretations of cuisine which present diners with modern interpretations of the finest Cantonese and Sichuan cuisine – a delectable balance of traditional, modern flavours and techniques. Lounge in the restaurant’s elegant dining area, set with oriental motifs against a backdrop of lush greenery.',
                'location' => 'Lobby, Hotel Tower 2\r\nNearest carpark: Central (Orange zone)',
                'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314075/Dining/blossom-1920x1080_wlo4st.jpg',
            ],
            [
                'restaurant_name' => 'BREAD STREET KITCHEN BY GORDON RAMSAY',
                'time_open' => '11:30 AM',
                'time_close' => '10:30 PM',
                'restaurant_type' => 'VEGETARIAN | WESTERN | CASUAL DINING | WATERFRONT | CELEBRITY CHEF RESTAURANT | BAR',
                'contact_email' => '',
                'contact_number' => '',
                'description' => 'With numerous television appearances and Michelin-Starred restaurants under his belt, Chef Gordon Ramsay and his cuisines truly need no introduction. The menu is a delightful selection of traditional British European fare. Beef Wellington, Fish & Chips and Roasted Cod are some of the signatures that shouldn’t be missed.',
                'location' => 'L1-81, The Shoppes\r\nNearest carpark: South (Blue zone)',
                'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314083/Dining/breadstreet-kitchen-porterhouse_vnledg.jpg',
            ],
            [
                'restaurant_name' => 'CANTON PARADISE',
                'time_open' => '10:30 AM',
                'time_close' => '11:00 PM',
                'restaurant_type' => 'CHINESE | OTHER ASIAN | VEGETARIAN | CASUAL DINING',
                'contact_number' => '+65 6688 7052',
                'description' => 'At Canton Paradise, expect all-day dim sum, roast meats, Hong Kong-style congee and wok-fried Cantonese dishes. The casual restaurant is perfect for couples and families alike, and offers views of the waterfront if you score the right seats.',
                'location' => 'L1-02, The Shoppes\r\nNearest carpark: North (Green zone)',
                'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314089/Dining/canton-paradise-1920x1080_xrxned.jpg',
            ],
            [
                'restaurant_name' => 'CÉ LA VI RESTAURANT',
                'time_open' => '12:00 PM',
                'time_close' => '11:00 PM',
                'restaurant_type' => 'OTHER ASIAN | WESTERN | FINE DINING | ROOFTOP | BAR',
                'contact_email' => 'celavi@hoteldelluna.com',
                'contact_number' => '+65 6508 2188',
                'description' => 'Overlooking the Singapore Straits and luminescent Gardens by the Bay, CÉ LA VI Restaurant is an alluring and contemporary dining institution. Curated by a powerhouse team of culinary maestros, CÉ LA VI unites key facets of Contemporary Asian cuisine ━ celebrating seasonality and the purity of flavour found in singular ingredients.',
                'location' => 'L57, Del Luna SkyPark, Hotel Tower 3\r\nNearest carpark: Central (Orange zone)',
                'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314093/Dining/ce-la-vi-gallery-updated-5_reltmo.jpg',
            ],
            [
                'restaurant_name' => 'DALLAS CAFE & BAR',
                'time_open' => '11:30 AM',
                'time_close' => '12:00 AM',
                'restaurant_type' => 'WESTERN | CAFÉ | WATERFRONT | BAR',
                'contact_email' => 'dallascafe@hoteldelluna.com',
                'contact_number' => '+65 6688 7153',
                'description' => 'Savour a delightful array of artisanal pizzas and the finest cheese and antipasto platters at Dallas Cafe & Bar. Complete your dining experience with draught beers, specially crafted cocktails and a selection of wines from Australia and New Zealand.',
                'location' => 'L1-85, The Shoppes\r\nNearest carpark: Central (Orange zone)',
                'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314103/Dining/dallas-cafe--bar-11_h8jiuc.jpg',
            ],
            [
                'restaurant_name' => 'DIN TAI FUNG',
                'time_open' => '10:30 AM',
                'time_close' => '12:00 AM',
                'restaurant_type' => 'CHINESE | CASUAL DINING',
                'contact_email' => 'dintaifung@hoteldelluna.com',
                'contact_number' => '+65 6634 9969',
                'description' => 'Ranked as one of the world\'s Top Ten Best Restaurants by the New York Times, Din Tai Fung has its roots dating back to Taiwan more than 60 years ago. With its famous signature Steamed Pork Xiao Long Bao and Steamed Chicken Soup, this authentic Taiwanese restaurant makes waves with branches in Singapore, Thailand, UK, Australia, China, Indonesia, Japan, Malaysia, Philippines, South Korea, UAE and USA.',
                'location' => 'B1-01, The Shoppes\r\nNearest carpark: South (Blue zone)',
                'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314107/Dining/din-tai-fung-desktop-masthead_ximyoq.jpg',
            ],
            [
                'restaurant_name' => 'FATT CHOI HOTPOT',
                'time_open' => '11:00 AM',
                'time_close' => '06:00 PM',
                'restaurant_type' => 'CHINESE | LOCAL | VEGETARIAN | CASUAL DINING | CASINO RESTAURANT',
                'contact_email' => 'fattchoihotpot@hoteldelluna.com',
                'contact_number' => '+65 6688 1567',
                'description' => 'Gather for a warm and nourishing meal at Fatt Choi Hotpot, where the quintessential hotpot dining experience is redefined. Customise the perfect hotpot for one or to share with an abundance of ingredients to choose from, including delectable seafood and the finest cuts of meat and vegetables.',
                'location' => 'B2M, Main Casino Floor\r\nNearest carpark: Central (Orange zone)',
                'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314111/Dining/fatt-choi-interior-2-1920x843_yiew5w.jpg',
            ],
            [
                'restaurant_name' => 'HAI DI LAO HOT POT',
                'time_open' => '10:30 AM',
                'time_close' => '06:00 PM',
                'restaurant_type' => 'CHINESE | CASUAL DINING',
                'contact_email' => 'haidilao@hoteldelluna.com',
                'contact_number' => '+65 6509 1611',
                'description' => 'The brand Haidilao was founded in 1994. With over 20 years of development, Haidilao International Holding Ltd. has become a world-renowned catering enterprise. Over the years, Haidilao has withstood the challenges of the market as well as customers, and has successfully forged a quality hot pot brand which has earned a reputation for itself. Haidilao combines kinds of characteristics of hot pot in many places of China. As a large-scale chain catering enterprise with operations all over the world, Haidilao adheres to integrity in business. It gives the highest priority to continuously improving the quality and safety of its food products, providing more thoughtful services to its customers while delivering healthier, safer and more nutritious food.',
                'location' => 'B2-01A, The Shoppes\r\nNearest carpark: South (Blue zone)',
                'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314111/Dining/hai-di-lao-1920x1080_eaass2.jpg',
            ],
            [
                'restaurant_name' => 'IPPUDO',
                'time_open' => '11:00 AM',
                'time_close' => '10:00 PM',
                'restaurant_type' => 'JAPANESE | CASUAL DINING',
                'contact_email' => 'ippudo@hoteldelluna.com',
                'contact_number' => '+65 6688 7064',
                'description' => 'Get your ramen fix at the award-winning IPPUDO, where classics and favourites such as Shoyu Ramen, Niku Soba and Tsukemen are served. Also try the restaurant’s unique side dishes such as samurai ribs and almond jelly noodles. If you would rather a takeaway, Kuro-Obi is located next door and offers chicken-based ramen in a thick and creamy broth.',
                'location' => 'B2-54, The Shoppes\r\nNearest carpark: North (Green zone)',
                'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314115/Dining/ippudo-1920x843-1_ekx9ei.jpg',
            ],
            [
                'restaurant_name' => 'JUMBO SIGNATURES',
                'time_open' => '11:30 AM',
                'time_close' => '03:00 AM',
                'restaurant_type' => 'LOCAL | CHINESE | OTHER ASIAN | VEGETARIAN | FINE DINING',
                'contact_email' => 'jumbosignatures@hoteldelluna.com',
                'contact_number' => '+65 6688 7023',
                'description' => 'JUMBO Signatures, the flagship premium dining concept of JUMBO Group, is taking your dining experience to greater heights. Set in a distinctive restaurant redolent of Singapore\'s heritage as a British colony, the familiar black-and-white features and intricate geometric patterns offer an alluring opportunity to immerse yourself in Singapore\'s tradition, culture and history through food fit for royalty. The flagship restaurant features Singapore\'s iconic flavours from the multiple dining concepts of JUMBO Group. From the ubiquitous Bak Kut Teh stewed to perfection by NG AH SIO Bak Kut Teh to the tantalizing Award Winning Chilli Crab mastered by JUMBO Seafood, JUMBO Signatures combines these quintessential tastes and elevates the Singapore dining experience through tasting menus and sommelier wine pairing.',
                'location' => 'B1-01B, The Shoppes\r\nNearest carpark: South (Blue zone)',
                'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314120/Dining/jumbo-gallery-1_b9bgud.jpg',
            ],
            [
                'restaurant_name' => 'ORIGIN + BLOOM',
                'time_open' => '07:00 AM',
                'time_close' => '08:30 PM',
                'restaurant_type' => 'WESTERN | CAFÉ',
                'contact_email' => '',
                'contact_number' => '+65 6688 8588',
                'description' => 'Flavours and ideas blossom into meaningful possibilities, right in the heart of a beautiful garden oasis. Here at Origin + Bloom, we draw inspiration from the finest artisans and craftsmen of Europe. Every ingredient we use is carefully considered – where it came from, how it is prepared and how the elements perfectly come together. Enjoy a menu of modern delights and timeless classics from our selection of freshly made gourmet breads, sandwiches and salads, paired with one of our signature brews such as contemporary cold-drip coffee. Then, take your pick from a delicious range of Instagram-worthy desserts such as the signature Mango, Piedmont Hazelnut Praline Macaé Chocolate Bar, Opera Cake and Salted Chocolate Orange Cake.',
                'location' => 'Lobby, Hotel Tower 2 & 3',
                'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314124/Dining/origin-and-bloom-gallery-1_torpoc.jpg',
            ],
            [
                'restaurant_name' => 'PS.CAFE',
                'time_open' => '10:30 AM',
                'time_close' => '10:30 PM',
                'restaurant_type' => 'WESTERN | CAFÉ | LOCAL | CASUAL DINING',
                'contact_email' => 'pscafe@hoteldelluna.com',
                'contact_number' => '+65 6708 9288',
                'description' => 'Hailed for its delicious comfort food and beautiful urban escapes PS.Cafe at Marina Bay Sands features a brand new menu comprising an array of delicious PS.Cafe classics, as well as new dishes exclusive to the venue. Parisian café culture was the inspiration behind the design story of PS.Cafe at Marina Bay Sands, which features the brand’s signature black and white aesthetic alongside thoughtful detailing to create a stunning yet intimate dining setting. Sheltered by parasols, guests visiting the island platform will find a private space that’s flooded with light, making it the perfect sanctuary to enjoy some delicious refreshments whilst watching the world go by.',
                'location' => 'Canal Level, B2-119\r\nNearest carpark: South (Blue zone)',
                'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314131/Dining/pscafe-desktop-masthead_zk8nny.jpg',
            ],
            [
                'restaurant_name' => 'RASAPURA MASTERS',
                'time_open' => '10:00 AM',
                'time_close' => '11:00 PM',
                'restaurant_type' => 'LOCAL | OTHER ASIAN | CASUAL DINING',
                'contact_email' => 'rasapuramasters@hoteldelluna.com',
                'contact_number' => '',
                'description' => 'Experience the food paradise that is Singapore as you sample a host of local and regional delights at Rasapura Masters, a space that evokes the city’s colonial past. Start your day at the food hall with a quintessentially Singaporean breakfast of toast, half-boiled eggs, and your choice of coffee — or kopi as the locals call it. For brunch, try dim sum, chicken rice or Butterfly Pea Flower Nasi Lemak. You can also choose Chinese, Japanese or Korean cuisine. Bubble tea and juicy chicken wings are perfect for a snack, or go for refreshing local desserts such as chendol and cheng tng. Come dinner, feast on local seafood dishes such as chilli crab, pepper crab and cereal prawn.',
                'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314135/Dining/rasapura-featured-1_rguq3l.jpg',
            ],
        ];

        foreach ($restaurants as $restaurantData) {
            Restaurant::create($restaurantData);
        }

        DB::table('restaurant_gallaries')->insert([
                ['restaurant_gallaries_id' => 1, 'restaurant_id' => 1, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314055/Dining/angelina-1920x1080-1_tjjwd0.jpg'],
                ['restaurant_gallaries_id' => 2, 'restaurant_id' => 1, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314055/Dining/angelina-1920x1080-2_j4tr2z.jpg'],
                ['restaurant_gallaries_id' => 4, 'restaurant_id' => 1, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314056/Dining/angelina-gallery-1920x1080-1_nqcrqy.jpg'],
                ['restaurant_gallaries_id' => 5, 'restaurant_id' => 1, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314056/Dining/angelina-gallery-1920x1080-3_axg4so.jpg'],
                ['restaurant_gallaries_id' => 6, 'restaurant_id' => 1, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314056/Dining/angelina-gallery-1920x1080-4_q1sfpb.jpg'],
                ['restaurant_gallaries_id' => 7, 'restaurant_id' => 1, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314057/Dining/Angelina-Masthead-1920x1080_wpomby.jpg'],
                ['restaurant_gallaries_id' => 8, 'restaurant_id' => 1, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314058/Dining/angelina-set-lunch-752x1336_kvmfs7.jpg'],
                ['restaurant_gallaries_id' => 10, 'restaurant_id' => 2, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314058/Dining/bacha-coffee-desktop-masthead_tforfg.jpg'],
                ['restaurant_gallaries_id' => 11, 'restaurant_id' => 2, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314059/Dining/bacha-coffee-gallery-1_avsuek.jpg'],
                ['restaurant_gallaries_id' => 12, 'restaurant_id' => 2, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314059/Dining/bacha-coffee-gallery-2_pgqkdu.jpg'],
                ['restaurant_gallaries_id' => 13, 'restaurant_id' => 2, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314060/Dining/bacha-coffee-gallery-3_fbl3tt.jpg'],
                ['restaurant_gallaries_id' => 15, 'restaurant_id' => 2, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314061/Dining/bacha-coffee-gallery-5_qnztra.jpg'],
                ['restaurant_gallaries_id' => 16, 'restaurant_id' => 2, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314062/Dining/bacha-coffee-gallery-6_ooyczf.jpg'],
                ['restaurant_gallaries_id' => 17, 'restaurant_id' => 2, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314062/Dining/bacha-coffee-gallery-7_aafcmy.jpg'],
                ['restaurant_gallaries_id' => 18, 'restaurant_id' => 2, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314062/Dining/bacha-coffee-gallery-8_sos666.jpg'],
                ['restaurant_gallaries_id' => 19, 'restaurant_id' => 2, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314063/Dining/bacha-festive-offerings-1080x1920_j4vgen.jpg'],
                ['restaurant_gallaries_id' => 20, 'restaurant_id' => 3, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314064/Dining/beanstro-1920x1080-1_a1gdj4.jpg'],
                ['restaurant_gallaries_id' => 21, 'restaurant_id' => 3, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314065/Dining/beanstro-1920x1080-2_a4ahmo.jpg'],
                ['restaurant_gallaries_id' => 24, 'restaurant_id' => 3, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314066/Dining/beanstro-gallery-1920x1080-2_xu70wv.jpg'],
                ['restaurant_gallaries_id' => 25, 'restaurant_id' => 3, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314066/Dining/beanstro-gallery-1920x1080-3_rfehvj.jpg'],
                ['restaurant_gallaries_id' => 26, 'restaurant_id' => 3, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314068/Dining/beanstro-gallery-1920x1080-4_dqiqxr.jpg'],
                ['restaurant_gallaries_id' => 27, 'restaurant_id' => 3, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314069/Dining/beanstro-gallery-1920x1080-7_dx5qxg.jpg'],
                ['restaurant_gallaries_id' => 28, 'restaurant_id' => 3, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314069/Dining/beanstro-gallery-1920x1080-8_svqk46.jpg'],
                ['restaurant_gallaries_id' => 29, 'restaurant_id' => 4, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314070/Dining/black-tap-crazyshake-752x1336_xhz9th.jpg'],
                ['restaurant_gallaries_id' => 30, 'restaurant_id' => 4, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314071/Dining/black-tap-gallery-1920x1080-1_lm3cec.jpg'],
                ['restaurant_gallaries_id' => 31, 'restaurant_id' => 4, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314071/Dining/black-tap-gallery-1920x1080-2_dhi80s.jpg'],
                ['restaurant_gallaries_id' => 32, 'restaurant_id' => 4, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314072/Dining/black-tap-gallery-1920x1080-3_sdb3d4.jpg'],
                ['restaurant_gallaries_id' => 33, 'restaurant_id' => 4, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314073/Dining/black-tap-gallery-1920x1080-5_vhpm1n.jpg'],
                ['restaurant_gallaries_id' => 34, 'restaurant_id' => 4, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314074/Dining/black-tap-gallery-1920x1080-7_kzan9o.jpg'],
                ['restaurant_gallaries_id' => 37, 'restaurant_id' => 5, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314076/Dining/blossom-1920x1080-1_hafnof.jpg'],
                ['restaurant_gallaries_id' => 38, 'restaurant_id' => 5, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314076/Dining/blossom-1920x1080-2_lhvlmu.jpg'],
                ['restaurant_gallaries_id' => 39, 'restaurant_id' => 5, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314077/Dining/blossom-gallery-1_ymb2nv.jpg'],
                ['restaurant_gallaries_id' => 40, 'restaurant_id' => 5, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314078/Dining/blossom-gallery-6_y4kffe.jpg'],
                ['restaurant_gallaries_id' => 41, 'restaurant_id' => 5, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314079/Dining/blossom-gallery-8_zn7bh7.jpg'],
                ['restaurant_gallaries_id' => 42, 'restaurant_id' => 5, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314079/Dining/blossom-gallery-14_wupko2.jpg'],
                ['restaurant_gallaries_id' => 43, 'restaurant_id' => 5, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314080/Dining/blossom-gallery-18_zvwlxa.jpg'],
                ['restaurant_gallaries_id' => 44, 'restaurant_id' => 6, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314082/Dining/breadstreet-kitchen-fish-and-chips_tbsm1g.jpg'],
                ['restaurant_gallaries_id' => 45, 'restaurant_id' => 6, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314082/Dining/breadstreet-kitchen-gallery-2_ilz06n.jpg'],
                ['restaurant_gallaries_id' => 46, 'restaurant_id' => 6, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314083/Dining/breadstreet-kitchen-gallery-3_yjeqjq.jpg'],
                ['restaurant_gallaries_id' => 48, 'restaurant_id' => 6, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314084/Dining/bsk-1920x1080_ccroom.jpg'],
                ['restaurant_gallaries_id' => 49, 'restaurant_id' => 6, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314085/Dining/bsk-1920x1080-3_t2trgt.jpg'],
                ['restaurant_gallaries_id' => 50, 'restaurant_id' => 6, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314086/Dining/bsk-gallery-1920x1080-2_wz9gve.jpg'],
                ['restaurant_gallaries_id' => 51, 'restaurant_id' => 6, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314086/Dining/bsk-gallery-1920x1080-7_md5nqr.jpg'],
                ['restaurant_gallaries_id' => 52, 'restaurant_id' => 7, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314090/Dining/canton-paradise-1920x1080-2_kaxq4v.jpg'],
                ['restaurant_gallaries_id' => 55, 'restaurant_id' => 7, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314087/Dining/canton-paradise-2_dwfjuq.jpg'],
                ['restaurant_gallaries_id' => 56, 'restaurant_id' => 7, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314089/Dining/canton-paradise-4_oy1bvg.jpg'],
                ['restaurant_gallaries_id' => 57, 'restaurant_id' => 8, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314091/Dining/ce-la-vi-gallery-updated-3_gtoona.jpg'],
                ['restaurant_gallaries_id' => 58, 'restaurant_id' => 8, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314092/Dining/ce-la-vi-gallery-updated-4_gvnkbj.jpg'],
                ['restaurant_gallaries_id' => 60, 'restaurant_id' => 8, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314094/Dining/ce-la-vi-gallery-updated-6_pvxmmk.jpg'],
                ['restaurant_gallaries_id' => 61, 'restaurant_id' => 8, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314094/Dining/clv-1920x1080_ejs4py.jpg'],
                ['restaurant_gallaries_id' => 62, 'restaurant_id' => 8, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314095/Dining/clv-1920x1080-1_fyjqsg.jpg'],
                ['restaurant_gallaries_id' => 64, 'restaurant_id' => 8, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314097/Dining/clv-1920x1080-2_xcsvpk.jpg'],
                ['restaurant_gallaries_id' => 65, 'restaurant_id' => 9, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314098/Dining/dallas-1920x1080_yr3ufh.jpg'],
                ['restaurant_gallaries_id' => 66, 'restaurant_id' => 9, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314099/Dining/dallas-1920x1080-3_hytrkb.jpg'],
                ['restaurant_gallaries_id' => 67, 'restaurant_id' => 9, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314098/Dining/dallas-1920x1080-1_uqe8lg.jpg'],
                ['restaurant_gallaries_id' => 68, 'restaurant_id' => 9, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314099/Dining/dallas-1920x1080-2_crcpm1.jpg'],
                ['restaurant_gallaries_id' => 69, 'restaurant_id' => 9, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314103/Dining/dallas-cafe--bar-10_n0v0am.jpg'],
                ['restaurant_gallaries_id' => 70, 'restaurant_id' => 9, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314102/Dining/dallas-cafe--bar-2_vqm9co.jpg'],
                ['restaurant_gallaries_id' => 71, 'restaurant_id' => 9, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314103/Dining/dallas-cafe--bar-11_h8jiuc.jpg'],
                ['restaurant_gallaries_id' => 72, 'restaurant_id' => 9, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314103/Dining/dallas-cafe--bar-6_oiy6qs.jpg'],
                ['restaurant_gallaries_id' => 74, 'restaurant_id' => 10, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314054/Dining/1920x843-fried-rice_hwqv0g.jpg'],
                ['restaurant_gallaries_id' => 75, 'restaurant_id' => 10, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314054/Dining/1920x843px_Image_Gallery_Sliced_Duck_in_Crispy_Spring_Onion_Pastry_k2d19h.jpg'],
                ['restaurant_gallaries_id' => 77, 'restaurant_id' => 10, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314106/Dining/din-tai-fung-1920x1080-1_iobuxg.jpg'],
                ['restaurant_gallaries_id' => 79, 'restaurant_id' => 10, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314107/Dining/din-tai-fung-1920x1080-4_iswvtl.jpg'],
                ['restaurant_gallaries_id' => 81, 'restaurant_id' => 10, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314107/Dining/din-tai-fung-gallery-1_rk1mrs.jpg'],
                ['restaurant_gallaries_id' => 82, 'restaurant_id' => 11, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314053/Dining/1-fc-1920x843_xbc9hz.jpg'],
                ['restaurant_gallaries_id' => 83, 'restaurant_id' => 11, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314054/Dining/2-fc_1920x843_omy08w.jpg'],
                ['restaurant_gallaries_id' => 84, 'restaurant_id' => 11, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314110/Dining/fatt-choi-1920x1080-1_zeyf6n.jpg'],
                ['restaurant_gallaries_id' => 85, 'restaurant_id' => 11, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314111/Dining/fatt-choi-video_aefi2r.jpg'],
                ['restaurant_gallaries_id' => 89, 'restaurant_id' => 12, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314114/Dining/hai-di-lao-1920x1080-2_kspb56.jpg'],
                ['restaurant_gallaries_id' => 90, 'restaurant_id' => 12, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314115/Dining/hai-di-lao-1920x1080-3_elwekw.jpg'],
                ['restaurant_gallaries_id' => 91, 'restaurant_id' => 12, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314115/Dining/hdl-gallery-1_jycjvn.jpg'],
                ['restaurant_gallaries_id' => 92, 'restaurant_id' => 12, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314115/Dining/hdl-gallery-3_ksdeto.jpg'],
                ['restaurant_gallaries_id' => 94, 'restaurant_id' => 13, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314116/Dining/ippudo-1920x843-2_mi6x1v.jpg'],
                ['restaurant_gallaries_id' => 95, 'restaurant_id' => 13, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314119/Dining/ippudo-1920x843-3_jvsvdm.jpg'],
                ['restaurant_gallaries_id' => 96, 'restaurant_id' => 13, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314119/Dining/ippudo-desktop-masthead_rfqby8.jpg'],
                ['restaurant_gallaries_id' => 97, 'restaurant_id' => 13, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314120/Dining/ippudo-gallery-10_kbzxyz.jpg'],
                ['restaurant_gallaries_id' => 99, 'restaurant_id' => 14, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314120/Dining/jumbo-gallery-2_mw6wbf.jpg'],
                ['restaurant_gallaries_id' => 100, 'restaurant_id' => 14, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314123/Dining/jumbo-gallery-5_ir05vd.jpg'],
                ['restaurant_gallaries_id' => 101, 'restaurant_id' => 14, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314123/Dining/jumbo-gallery-6_tfsy7w.jpg'],
                ['restaurant_gallaries_id' => 102, 'restaurant_id' => 14, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314123/Dining/jumbo-gallery-10_qepown.jpg'],
                ['restaurant_gallaries_id' => 105, 'restaurant_id' => 15, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314124/Dining/ob-signature_uairks.jpg'],
                ['restaurant_gallaries_id' => 107, 'restaurant_id' => 15, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314124/Dining/origin-and-bloom-gallery-1_torpoc.jpg'],
                ['restaurant_gallaries_id' => 108, 'restaurant_id' => 15, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314127/Dining/origin-and-bloom-gallery-7_rpd30w.jpg'],
                ['restaurant_gallaries_id' => 109, 'restaurant_id' => 15, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314128/Dining/origin-and-bloom-gallery-9_pxnbno.jpg'],
                ['restaurant_gallaries_id' => 110, 'restaurant_id' => 15, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314127/Dining/origin-and-bloom-gallery-5_rnnttl.jpg'],
                ['restaurant_gallaries_id' => 111, 'restaurant_id' => 15, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314127/Dining/origin-and-bloom-gallery-3_vgs1gv.jpg'],
                ['restaurant_gallaries_id' => 113, 'restaurant_id' => 16, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314131/Dining/ps-cafe-gallery-1_x4bx5l.jpg'],
                ['restaurant_gallaries_id' => 114, 'restaurant_id' => 16, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314131/Dining/ps-cafe-gallery-2_qaje4z.jpg'],
                ['restaurant_gallaries_id' => 115, 'restaurant_id' => 16, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314132/Dining/ps-cafe-gallery-5_njolxf.jpg'],
                ['restaurant_gallaries_id' => 116, 'restaurant_id' => 16, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314132/Dining/ps-cafe-gallery-3_zmhjaa.jpg'],
                ['restaurant_gallaries_id' => 117, 'restaurant_id' => 16, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314132/Dining/ps-cafe-gallery-4_bo3xeh.jpg'],
                ['restaurant_gallaries_id' => 119, 'restaurant_id' => 17, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314136/Dining/rasapura-featured-3_emxmy9.jpg'],
                ['restaurant_gallaries_id' => 120, 'restaurant_id' => 17, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314135/Dining/rasapura-featured-1_rguq3l.jpg'],
                ['restaurant_gallaries_id' => 121, 'restaurant_id' => 17, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314136/Dining/rasapura-featured-2_hounuq.jpg'],
                ['restaurant_gallaries_id' => 122, 'restaurant_id' => 17, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314141/Dining/rasapura-gallery-10_ymt9jx.jpg'],
                ['restaurant_gallaries_id' => 123, 'restaurant_id' => 17, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314139/Dining/rasapura-gallery-7_ivvbju.jpg'],
                ['restaurant_gallaries_id' => 124, 'restaurant_id' => 17, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314136/Dining/rasapura-gallery-1_ckbuyn.jpg'],
                ['restaurant_gallaries_id' => 125, 'restaurant_id' => 17, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314137/Dining/rasapura-gallery-3_ee0q0w.jpg'],
                ['restaurant_gallaries_id' => 126, 'restaurant_id' => 17, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314140/Dining/rasapura-gallery-9_hfbj0l.jpg'],
                ['restaurant_gallaries_id' => 127, 'restaurant_id' => 17, 'picture' => 'https://res.cloudinary.com/dk0ystu6k/image/upload/v1705314138/Dining/rasapura-gallery-6_ww0fso.jpg']
        ]);

        $room = Room::factory(150)->create();
    }
}
